#Requires -Version 5.1
<#
.SYNOPSIS
  Install or upgrade Open Jarvis on a Windows fleet host.

.PARAMETER InstallRoot
  Directory containing the release (package.json, server/, app/, deploy/).

.PARAMETER DataDir
  Per-machine data root (Postgres volume, workspace, backups). Default C:\hermes-data

.PARAMETER PublicUrl
  Browser-facing origin, e.g. https://jarvis-042.corp.example.com:3001

.PARAMETER FleetEnv
  Path to fleet-wide env file (LDAP, LLM gateway). Default deploy\fleet.env

.EXAMPLE
  .\install-windows.ps1 -PublicUrl "https://jarvis-042.corp.example.com:3001"
#>
param(
  [string]$InstallRoot = (Split-Path -Parent $PSScriptRoot),
  [string]$DataDir = 'C:\hermes-data',
  [Parameter(Mandatory = $true)]
  [string]$PublicUrl,
  [string]$FleetEnv = '',
  [switch]$SkipBuild
)

$ErrorActionPreference = 'Stop'
$InstallRoot = (Resolve-Path $InstallRoot).Path
if (-not $FleetEnv) { $FleetEnv = Join-Path $InstallRoot 'deploy\fleet.env' }

function New-RandomSecret {
  $bytes = New-Object byte[] 32
  [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
  return [Convert]::ToBase64String($bytes)
}

Write-Host "Install root: $InstallRoot"
Write-Host "Data dir:     $DataDir"
Write-Host "Public URL:   $PublicUrl"

if (-not (Test-Path $FleetEnv)) {
  Write-Error "Fleet env missing: $FleetEnv — copy deploy\fleet.env.example to deploy\fleet.env"
}

New-Item -ItemType Directory -Force -Path $DataDir | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $DataDir 'workspace') | Out-Null

$envPath = Join-Path $InstallRoot '.env'
$lines = @(
  "# Generated by deploy/install-windows.ps1 $(Get-Date -Format o)",
  "HERMES_DATA_DIR=$DataDir",
  "HOST=0.0.0.0",
  "PORT=3001",
  "BETTER_AUTH_URL=$PublicUrl",
  "HERMES_PUBLIC_URL=$PublicUrl",
  "BETTER_AUTH_SECRET=$(New-RandomSecret)",
  "DATABASE_URL=postgres://hermes:hermes@localhost:5433/hermes",
  "HERMES_ALLOW_DB_PATH_SETTINGS=0",
  "HERMES_SERVE_STATIC=1",
  "ALLOW_SIGNUP=false"
)
Get-Content $FleetEnv | ForEach-Object {
  if ($_ -match '^\s*#' -or $_ -match '^\s*$') { return }
  if ($_ -match '^HERMES_DATA_DIR=') { return }
  if ($_ -match '^BETTER_AUTH_') { return }
  if ($_ -match '^HOST=') { return }
  if ($_ -match '^PORT=') { return }
  if ($_ -match '^DATABASE_URL=') { return }
  $lines += $_
}
$lines | Set-Content -Encoding utf8 $envPath
Write-Host "Wrote $envPath"

$env:HERMES_DATA_DIR = $DataDir
Push-Location $InstallRoot
try {
  if (-not $SkipBuild) {
    Write-Host 'Building app + server...'
    bun run build
  }
  Write-Host 'Starting Postgres...'
  bun run db:up
  Start-Sleep -Seconds 8
  Write-Host 'Running migrations...'
  bun run migrate
  Push-Location (Join-Path $InstallRoot 'server')
  try { bun run scripts/check-auth-db.ts } finally { Pop-Location }
  Write-Host 'Health check...'
  $env:HERMES_SERVE_STATIC = '1'
  $proc = Start-Process -FilePath 'bun' -ArgumentList @('run', 'server/src/index.ts') -WorkingDirectory (Join-Path $InstallRoot 'server') -PassThru -WindowStyle Hidden
  Start-Sleep -Seconds 6
  try {
    $health = Invoke-RestMethod -Uri "$PublicUrl/api/health" -TimeoutSec 10
    Write-Host "Health OK: ldapEnabled=$($health.ldapEnabled) authRequired=$($health.authRequired)"
  } catch {
    $health = Invoke-RestMethod -Uri 'http://127.0.0.1:3001/api/health' -TimeoutSec 10
    Write-Host "Health OK (localhost): ldapEnabled=$($health.ldapEnabled) authRequired=$($health.authRequired)"
  } finally {
    if ($proc -and -not $proc.HasExited) { Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue }
  }
} finally {
  Pop-Location
}

Write-Host @"

Next steps:
  1. Register a Windows Service or scheduled task: bun run start (from $InstallRoot)
  2. Open $PublicUrl/login and sign in with LDAP
  3. Probe LDAP: bun run server/scripts/ldap-probe.ts <user> <pass>

"@