#!/usr/bin/env bash
# Install or upgrade Open Jarvis on a Linux fleet host.
# Usage:
#   sudo ./deploy/install-linux.sh --public-url https://jarvis-042.corp.example.com:3001
set -euo pipefail

INSTALL_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DATA_DIR="${HERMES_DATA_DIR:-/var/lib/hermes}"
PUBLIC_URL=""
FLEET_ENV="${INSTALL_ROOT}/deploy/fleet.env"
SKIP_BUILD=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --install-root) INSTALL_ROOT="$2"; shift 2 ;;
    --data-dir) DATA_DIR="$2"; shift 2 ;;
    --public-url) PUBLIC_URL="$2"; shift 2 ;;
    --fleet-env) FLEET_ENV="$2"; shift 2 ;;
    --skip-build) SKIP_BUILD=1; shift ;;
    -h|--help)
      echo "Usage: $0 --public-url https://HOST:3001 [--data-dir /var/lib/hermes]"
      exit 0
      ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

if [[ -z "$PUBLIC_URL" ]]; then
  echo "ERROR: --public-url is required (per-host browser origin)"
  exit 1
fi

if [[ ! -f "$FLEET_ENV" ]]; then
  echo "ERROR: fleet env missing — copy deploy/fleet.env.example to deploy/fleet.env"
  exit 1
fi

command -v bun >/dev/null || { echo "ERROR: bun not on PATH"; exit 1; }
command -v docker >/dev/null || { echo "ERROR: docker not on PATH"; exit 1; }

mkdir -p "$DATA_DIR/workspace"
SECRET="$(openssl rand -base64 32)"

{
  echo "# Generated by deploy/install-linux.sh $(date -Iseconds)"
  echo "HERMES_DATA_DIR=$DATA_DIR"
  echo "HOST=0.0.0.0"
  echo "PORT=3001"
  echo "BETTER_AUTH_URL=$PUBLIC_URL"
  echo "HERMES_PUBLIC_URL=$PUBLIC_URL"
  echo "BETTER_AUTH_SECRET=$SECRET"
  echo "DATABASE_URL=postgres://hermes:hermes@localhost:5433/hermes"
  echo "HERMES_ALLOW_DB_PATH_SETTINGS=0"
  echo "HERMES_SERVE_STATIC=1"
  echo "ALLOW_SIGNUP=false"
  grep -v -E '^(HERMES_DATA_DIR|BETTER_AUTH_|HOST=|PORT=|DATABASE_URL=|#|$)' "$FLEET_ENV" || true
} > "$INSTALL_ROOT/.env"

export HERMES_DATA_DIR="$DATA_DIR"
cd "$INSTALL_ROOT"

if [[ "$SKIP_BUILD" -eq 0 ]]; then
  bun run build
fi

bun run db:up
sleep 8
bun run migrate
cd "$INSTALL_ROOT/server" && bun run scripts/check-auth-db.ts
cd "$INSTALL_ROOT"

echo "Install complete. Start with: bun run start"
echo "Login: ${PUBLIC_URL}/login"
echo "LDAP probe: bun run server/scripts/ldap-probe.ts USER PASS"
