import type { JsonSchema } from './helpers'

/** OpenAPI components.schemas — mirrors @hermes/shared DTOs + DB tables. */
export const schemas: Record<string, JsonSchema> = {
  ApiError: {
    type: 'object',
    properties: {
      error: { type: 'string' },
      code: { type: 'string' },
      message: { type: 'string' },
      detail: {},
      details: {},
    },
    required: ['error'],
  },
  DeletedResponse: {
    type: 'object',
    properties: { deleted: { type: 'boolean' } },
    required: ['deleted'],
  },
  OkResponse: {
    type: 'object',
    properties: { ok: { type: 'boolean' } },
    required: ['ok'],
  },
  HealthResponse: {
    type: 'object',
    properties: {
      ok: { type: 'boolean' },
      version: { type: 'string' },
      db: { type: 'boolean' },
      llm: {
        type: 'object',
        properties: {
          mode: { type: 'string', enum: ['mock', 'live'] },
          mock: { type: 'boolean' },
          baseUrl: { type: 'string' },
          model: { type: ['string', 'null'] },
        },
        required: ['mode', 'mock', 'baseUrl', 'model'],
      },
    },
    required: ['ok', 'version', 'db', 'llm'],
  },

  Session: {
    'x-db-table': 'sessions',
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      title: { type: 'string' },
      groupName: { type: ['string', 'null'] },
      profileId: { type: ['string', 'null'], format: 'uuid' },
      pinned: { type: 'boolean' },
      archived: { type: 'boolean' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['id', 'title', 'pinned', 'archived', 'createdAt', 'updatedAt'],
  },
  Message: {
    'x-db-table': 'messages',
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      sessionId: { type: 'string', format: 'uuid' },
      runId: { type: 'string' },
      role: { type: 'string', enum: ['user', 'assistant', 'system', 'tool'] },
      content: { type: 'string' },
      toolName: { type: ['string', 'null'] },
      toolArgs: { type: ['object', 'null'], additionalProperties: true },
      toolResult: { type: ['object', 'null'], additionalProperties: true },
      thinking: { type: ['string', 'null'] },
      a2ui: { type: ['object', 'null'], additionalProperties: true },
      tokens: { type: 'number' },
      createdAt: { type: 'string', format: 'date-time' },
    },
    required: ['id', 'sessionId', 'role', 'content', 'createdAt'],
  },
  Skill: {
    'x-db-table': 'skills',
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      name: { type: 'string' },
      slug: { type: 'string' },
      description: { type: 'string' },
      bodyMd: { type: 'string' },
      source: { type: 'string' },
      path: { type: ['string', 'null'] },
      contentHash: { type: ['string', 'null'] },
      triggers: { type: ['array', 'null'], items: { type: 'string' } },
      enabled: { type: 'boolean' },
      lastSyncedAt: { type: ['string', 'null'], format: 'date-time' },
      missingOnDisk: { type: 'boolean' },
      usageCount: { type: 'integer' },
      successCount: { type: 'integer' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['id', 'name', 'slug', 'bodyMd', 'enabled'],
  },
  SkillsSyncResult: {
    type: 'object',
    properties: {
      synced: { type: 'integer' },
      created: { type: 'integer' },
      updated: { type: 'integer' },
      unchanged: { type: 'integer' },
      missing: { type: 'integer' },
      recreated: { type: 'integer' },
      lastSyncedAt: { type: 'string', format: 'date-time' },
      git: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            url: { type: 'string' },
            synced: { type: 'integer' },
          },
        },
      },
    },
  },
  SkillsMeta: {
    type: 'object',
    properties: {
      lastSyncedAt: { type: ['string', 'null'] },
      skillsDir: { type: 'string' },
      total: { type: 'integer' },
      enabled: { type: 'integer' },
      missing: { type: 'integer' },
    },
  },
  SkillsSourcesResponse: {
    type: 'object',
    properties: { sources: { type: 'array', items: { type: 'string' } } },
    required: ['sources'],
  },
  MemoryEntry: {
    'x-db-table': 'memory',
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      kind: { type: 'string', enum: ['semantic', 'episodic', 'preference'] },
      content: { type: 'string' },
      sourceSession: { type: ['string', 'null'] },
      importance: { type: 'number' },
      createdAt: { type: 'string', format: 'date-time' },
      lastAccessed: { type: 'string', format: 'date-time' },
    },
    required: ['id', 'kind', 'content', 'importance', 'createdAt'],
  },
  CronWorkflow: {
    type: 'object',
    description:
      'Enterprise workflow config persisted in `cron_jobs.workflow`. `systemKind` selects a deterministic maintenance runner.',
    properties: {
      version: { type: 'integer', enum: [1] },
      intent: { type: 'string' },
      systemKind: {
        type: 'string',
        enum: ['db-consistency', 'bug-bounty'],
        description:
          'When set, cron fires a check-and-fix maintenance handler instead of an LLM agent turn.',
      },
      timezone: { type: 'string', default: 'UTC' },
      mcpServerIds: { type: 'array', items: { type: 'string', format: 'uuid' } },
      skillIds: { type: 'array', items: { type: 'string', format: 'uuid' } },
      profileId: { type: ['string', 'null'], format: 'uuid' },
      headlessAutoApprove: { type: 'boolean', default: false },
      retry: {
        type: 'object',
        properties: {
          maxAttempts: { type: 'integer', minimum: 1, maximum: 10 },
          backoffSec: { type: 'integer', minimum: 0, maximum: 3600 },
        },
      },
      steps: { type: 'array', items: { type: 'object', additionalProperties: true } },
      ui: { type: 'object', additionalProperties: true },
    },
    required: ['version'],
  },
  CronJob: {
    'x-db-table': 'cron_jobs',
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      name: { type: 'string' },
      schedule: {
        type: 'string',
        description: 'Cron expression. Built-in system jobs use `*/5 * * * *`.',
        example: '*/5 * * * *',
      },
      prompt: { type: 'string' },
      profileId: { type: ['string', 'null'] },
      enabled: { type: 'boolean' },
      lastRun: { type: ['string', 'null'], format: 'date-time' },
      nextRun: { type: ['string', 'null'], format: 'date-time' },
      timezone: { type: 'string' },
      workflow: { $ref: '#/components/schemas/CronWorkflow' },
      mcpServerIds: { type: 'array', items: { type: 'string', format: 'uuid' } },
      skillIds: { type: 'array', items: { type: 'string', format: 'uuid' } },
      updatedAt: { type: ['string', 'null'], format: 'date-time' },
    },
    required: ['id', 'name', 'schedule', 'prompt', 'enabled', 'timezone'],
  },
  CronRun: {
    'x-db-table': 'cron_runs',
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      jobId: { type: 'string', format: 'uuid' },
      startedAt: { type: 'string', format: 'date-time' },
      finishedAt: { type: ['string', 'null'], format: 'date-time' },
      status: { type: 'string', enum: ['running', 'completed', 'failed'] },
      sessionId: { type: ['string', 'null'] },
      error: { type: ['string', 'null'] },
      detail: {
        type: ['object', 'null'],
        additionalProperties: true,
        description:
          'Per-run snapshot. System jobs include `detail.maintenance` with `{ kind, ok, checked, fixed, findings }`.',
      },
    },
    required: ['id', 'jobId', 'startedAt', 'status'],
  },
  CronMaintenanceResult: {
    type: 'object',
    properties: {
      kind: { type: 'string', enum: ['db-consistency', 'bug-bounty'] },
      ok: { type: 'boolean' },
      checked: { type: 'integer' },
      fixed: { type: 'integer' },
      findings: { type: 'array', items: { type: 'string' } },
      detail: { type: 'object', additionalProperties: true },
    },
    required: ['kind', 'ok', 'checked', 'fixed', 'findings'],
  },
  CronSystemJobsResponse: {
    type: 'object',
    properties: {
      schedule: {
        type: 'string',
        description: 'Default schedule for built-in maintenance jobs',
        example: '*/5 * * * *',
      },
      catalog: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            name: { type: 'string' },
            kind: { type: 'string', enum: ['db-consistency', 'bug-bounty'] },
            schedule: { type: 'string' },
            prompt: { type: 'string' },
          },
          required: ['name', 'kind', 'schedule', 'prompt'],
        },
      },
      jobs: { type: 'array', items: { $ref: '#/components/schemas/CronJob' } },
    },
    required: ['schedule', 'catalog', 'jobs'],
  },
  CronValidateResponse: {
    type: 'object',
    properties: {
      valid: { type: 'boolean' },
      preview: { type: 'string' },
      nextRun: { type: ['string', 'null'] },
    },
    required: ['valid', 'preview', 'nextRun'],
  },
  CronWizardPreviewResponse: {
    type: 'object',
    properties: {
      schedule: { oneOf: [{ $ref: '#/components/schemas/CronValidateResponse' }, { type: 'null' }] },
      mcpServers: { type: 'array', items: { type: 'object', additionalProperties: true } },
      unknownMcpIds: { type: 'array', items: { type: 'string' } },
      skills: { type: 'array', items: { type: 'object', additionalProperties: true } },
      unknownSkillIds: { type: 'array', items: { type: 'string' } },
    },
  },
  Profile: {
    'x-db-table': 'profiles',
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      name: { type: 'string' },
      systemPrompt: { type: 'string' },
      model: { type: 'string' },
      temperature: { type: 'number' },
      provider: { type: 'string', enum: ['native', 'agui-remote', 'hermes-python'] },
      providerConfig: { type: ['object', 'null'], additionalProperties: true },
      settings: { type: ['object', 'null'], additionalProperties: true },
    },
    required: ['id', 'name', 'systemPrompt', 'model', 'temperature', 'provider'],
  },
  McpServer: {
    'x-db-table': 'mcp_servers',
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      name: { type: 'string' },
      description: { type: ['string', 'null'] },
      transport: { type: 'string', enum: ['stdio', 'http'] },
      command: { type: ['string', 'null'] },
      url: { type: ['string', 'null'] },
      env: { type: ['object', 'null'], additionalProperties: { type: 'string' } },
      headers: { type: ['object', 'null'], additionalProperties: { type: 'string' } },
      enabled: { type: 'boolean' },
      toolWhitelist: { type: ['array', 'null'], items: { type: 'string' } },
      httpPreferSse: { type: 'boolean' },
      timeoutMs: { type: ['integer', 'null'] },
      autoReconnect: { type: 'boolean' },
      lastStatus: {
        type: ['string', 'null'],
        enum: ['connected', 'disconnected', 'error', 'reconnecting', null],
      },
      lastError: { type: ['string', 'null'] },
      lastConnectedAt: { type: ['string', 'null'], format: 'date-time' },
      lastTestedAt: { type: ['string', 'null'], format: 'date-time' },
      discoveredTools: { type: ['array', 'null'], items: { type: 'object' } },
      discoveredResources: { type: ['array', 'null'], items: { type: 'object' } },
      discoveredPrompts: { type: ['array', 'null'], items: { type: 'object' } },
      metadata: { type: ['object', 'null'], additionalProperties: true },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['id', 'name', 'transport', 'enabled'],
  },
  McpConnectionEvent: {
    'x-db-table': 'mcp_connection_events',
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      serverId: { type: 'string', format: 'uuid' },
      eventType: { type: 'string' },
      status: { type: ['string', 'null'] },
      transportKind: { type: ['string', 'null'] },
      detail: { type: ['object', 'null'], additionalProperties: true },
      createdAt: { type: 'string', format: 'date-time' },
    },
    required: ['id', 'serverId', 'eventType', 'createdAt'],
  },
  McpListResponse: {
    type: 'object',
    properties: {
      servers: { type: 'array', items: { $ref: '#/components/schemas/McpServer' } },
      states: { type: 'object', additionalProperties: true },
    },
    required: ['servers', 'states'],
  },
  ApiToken: {
    'x-db-table': 'api_tokens',
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      name: { type: 'string' },
      token: { type: 'string', description: 'Present only on create' },
      scopes: { type: 'array', items: { type: 'string' } },
      lastUsedAt: { type: ['string', 'null'], format: 'date-time' },
      createdAt: { type: 'string', format: 'date-time' },
    },
    required: ['id', 'name', 'scopes', 'createdAt'],
  },
  ApiTokenListResponse: {
    type: 'object',
    properties: {
      tokens: { type: 'array', items: { $ref: '#/components/schemas/ApiToken' } },
    },
    required: ['tokens'],
  },
  SettingRow: {
    'x-db-table': 'settings',
    type: 'object',
    properties: {
      key: { type: 'string' },
      value: {},
      sessionId: { type: ['string', 'null'] },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['key', 'value'],
  },
  SettingsMap: {
    type: 'object',
    additionalProperties: true,
    description: 'Key/value settings; sensitive values are masked on read.',
  },
  SettingsExportResponse: {
    type: 'object',
    properties: {
      exportedAt: { type: 'string', format: 'date-time' },
      product: { type: 'string' },
      sessions: { type: 'array', items: { $ref: '#/components/schemas/Session' } },
      memory: { type: 'array', items: { $ref: '#/components/schemas/MemoryEntry' } },
      skills: { type: 'array', items: { $ref: '#/components/schemas/Skill' } },
      profiles: { type: 'array', items: { $ref: '#/components/schemas/Profile' } },
      settings: { $ref: '#/components/schemas/SettingsMap' },
    },
    required: ['exportedAt', 'product', 'sessions', 'memory', 'skills', 'profiles', 'settings'],
  },
  RunEvent: {
    'x-db-table': 'run_events',
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      runId: { type: 'string', format: 'uuid' },
      sessionId: { type: ['string', 'null'] },
      seq: { type: 'integer' },
      eventType: { type: 'string' },
      payload: { type: 'object', additionalProperties: true },
      createdAt: { type: 'string', format: 'date-time' },
    },
    required: ['id', 'runId', 'seq', 'eventType', 'payload', 'createdAt'],
  },
  SearchResult: {
    type: 'object',
    properties: {
      kind: { type: 'string' },
      id: { type: 'string' },
      snippet: { type: 'string' },
      score: { type: 'number' },
      sessionId: { type: 'string' },
      runId: { type: ['string', 'null'] },
      path: { type: ['string', 'null'] },
      title: { type: ['string', 'null'] },
      sourceType: { type: 'string' },
    },
    required: ['kind', 'id', 'snippet'],
  },
  SearchResponse: {
    type: 'object',
    properties: {
      query: { type: 'string' },
      results: { type: 'array', items: { $ref: '#/components/schemas/SearchResult' } },
    },
    required: ['query', 'results'],
  },
  WorkspaceEntry: {
    type: 'object',
    properties: {
      name: { type: 'string' },
      type: { type: 'string', enum: ['file', 'dir'] },
      path: { type: 'string' },
    },
    required: ['name', 'type', 'path'],
  },
  WorkspaceTreeResponse: {
    type: 'object',
    properties: {
      path: { type: 'string' },
      entries: { type: 'array', items: { $ref: '#/components/schemas/WorkspaceEntry' } },
    },
    required: ['path', 'entries'],
  },
  WorkspaceGitStatus: {
    type: 'object',
    properties: {
      isRepo: { type: 'boolean' },
      dirty: { type: 'boolean' },
      files: { type: 'array', items: { type: 'string' } },
    },
    required: ['isRepo', 'dirty', 'files'],
  },
  WorkspaceFileResponse: {
    type: 'object',
    properties: {
      path: { type: 'string' },
      content: { type: ['string', 'null'] },
      encoding: { type: 'string', enum: ['utf8', 'base64'] },
      mime: { type: 'string' },
      contentBase64: { type: 'string' },
    },
    required: ['path', 'encoding', 'mime'],
  },
  WorkspaceFileWriteBody: {
    type: 'object',
    properties: {
      path: { type: 'string' },
      content: { type: 'string' },
      contentBase64: { type: 'string' },
      encoding: { type: 'string', enum: ['utf8', 'base64'] },
    },
    required: ['path'],
  },
  WorkspaceUploadBody: {
    type: 'object',
    properties: {
      path: { type: 'string' },
      content: { type: 'string' },
      contentBase64: { type: 'string' },
      encoding: { type: 'string', enum: ['utf8', 'base64'] },
    },
    required: ['path'],
  },
  WorkspaceUploadResponse: {
    type: 'object',
    properties: {
      ok: { type: 'boolean' },
      path: { type: 'string' },
      name: { type: 'string' },
    },
    required: ['ok', 'path', 'name'],
  },
  CoworkTask: {
    type: 'object',
    description: 'Open Cowork work-request (file-backed outbox).',
    properties: {
      taskId: { type: 'string' },
      status: { type: 'string', enum: ['queued', 'running', 'done', 'failed', 'aborted'] },
      goal: { type: ['string', 'null'] },
      deliverableType: {
        type: ['string', 'null'],
        enum: ['presentation', 'word', 'spreadsheet', 'pdf', 'other', null],
      },
      sessionId: { type: ['string', 'null'] },
      files: { type: 'array', items: { type: 'string' } },
      summary: { type: ['string', 'null'] },
      error: { type: ['string', 'null'] },
      createdAt: { type: 'string', format: 'date-time' },
      finishedAt: { type: ['string', 'null'], format: 'date-time' },
    },
    required: ['taskId', 'status', 'files', 'createdAt'],
  },
  CoworkSetupResponse: {
    type: 'object',
    properties: {
      configured: { type: 'boolean' },
      exe: { type: 'string' },
      exeExists: { type: 'boolean' },
      workspace: { type: 'string' },
      hint: { type: 'string' },
      releasesUrl: { type: 'string' },
      downloadUrl: { type: 'string' },
      code: { type: 'string' },
    },
    required: ['configured', 'exe', 'exeExists', 'workspace', 'hint'],
  },
  CreateCoworkTaskBody: {
    type: 'object',
    properties: {
      goal: { type: 'string' },
      deliverableType: {
        type: 'string',
        enum: ['presentation', 'word', 'spreadsheet', 'pdf', 'other'],
      },
      files: {
        type: 'array',
        items: {
          oneOf: [
            { type: 'string' },
            {
              type: 'object',
              properties: {
                sourcePath: { type: 'string' },
                name: { type: 'string' },
              },
              required: ['sourcePath'],
            },
          ],
        },
      },
      autoApprove: { type: 'boolean' },
    },
    required: ['goal', 'deliverableType'],
  },
  CreateCoworkTaskResponse: {
    type: 'object',
    properties: {
      taskId: { type: 'string' },
      status: { type: 'string' },
      sessionId: { type: ['string', 'null'] },
    },
    required: ['taskId', 'status'],
  },
  CoworkTaskListResponse: {
    type: 'object',
    properties: {
      tasks: { type: 'array', items: { $ref: '#/components/schemas/CoworkTask' } },
    },
    required: ['tasks'],
  },
  CoworkTaskDetail: {
    allOf: [
      { $ref: '#/components/schemas/CoworkTask' },
      {
        type: 'object',
        properties: {
          statusJson: { type: ['object', 'null'], additionalProperties: true },
          outboxFiles: { type: 'array', items: { type: 'string' } },
        },
      },
    ],
  },
  AbortCoworkTaskResponse: {
    type: 'object',
    properties: {
      ok: { type: 'boolean' },
      taskId: { type: 'string' },
      status: { type: 'string' },
      error: { type: 'string' },
    },
    required: ['ok', 'taskId', 'status'],
  },
  OfficeConfigResponse: {
    type: 'object',
    properties: {
      configured: { type: 'boolean' },
      missingEnv: { type: 'array', items: { type: 'string' } },
      redirectUri: { type: 'string' },
      tenantId: { type: 'string' },
      autoSso: { type: 'boolean' },
      azurePlatform: { type: 'string', enum: ['Web'] },
      flow: { type: 'string' },
      purpose: { type: 'string' },
      scopes: { type: 'array', items: { type: 'string' } },
    },
    required: ['configured', 'missingEnv', 'redirectUri'],
  },
  OfficeStatusResponse: {
    allOf: [
      { $ref: '#/components/schemas/OfficeConfigResponse' },
      {
        type: 'object',
        properties: {
          connected: { type: 'boolean' },
          account: { type: ['object', 'null'], additionalProperties: true },
          artifactScopes: { type: 'array', items: { type: 'string' } },
          grantedScopes: { type: 'array', items: { type: 'string' } },
        },
        required: ['connected'],
      },
    ],
  },
  OfficeConnectResponse: {
    type: 'object',
    properties: { authUrl: { type: 'string', format: 'uri' } },
    required: ['authUrl'],
  },
  OfficeDisconnectResponse: {
    type: 'object',
    properties: { connected: { type: 'boolean', enum: [false] } },
    required: ['connected'],
  },
  OfficeBriefingResponse: {
    type: 'object',
    properties: {
      live: { type: 'boolean' },
      syncedAt: { type: 'string', format: 'date-time' },
      connected: { type: 'boolean' },
      configured: { type: 'boolean' },
      account: {},
      stats: { type: ['object', 'null'], additionalProperties: true },
      agenda: { type: 'array', items: { type: 'object', additionalProperties: true } },
      insights: { type: 'array', items: { type: 'string' } },
      actions: { type: 'array', items: { type: 'string' } },
      note: { type: 'string' },
      message: { type: 'string' },
      error: { type: 'string' },
    },
    required: ['live', 'connected', 'agenda'],
  },
  ApprovalConfig: {
    type: 'object',
    properties: {
      autoApproveAll: { type: 'boolean' },
      toolWhitelist: { type: 'array', items: { type: 'string' } },
      sessionWhitelist: { type: 'array', items: { type: 'string' } },
    },
    required: ['autoApproveAll', 'toolWhitelist', 'sessionWhitelist'],
  },
  UpdateApprovalConfigBody: {
    type: 'object',
    properties: {
      autoApproveAll: { type: 'boolean' },
      toolWhitelist: { type: 'array', items: { type: 'string' } },
    },
  },
  ResolveApprovalBody: {
    type: 'object',
    properties: {
      toolCallId: { type: 'string' },
      decision: { type: 'string', enum: ['approve', 'reject', 'always', 'always_tool'] },
    },
    required: ['toolCallId', 'decision'],
  },
  ResolveApprovalResponse: {
    type: 'object',
    properties: { ok: { type: 'boolean', enum: [true] } },
    required: ['ok'],
  },
  IndexerStatusResponse: {
    type: 'object',
    properties: {
      queueDepth: { type: 'integer' },
      retryingJobs: { type: 'integer' },
      failedJobs: { type: 'integer' },
      indexedDocuments: { type: 'integer' },
      indexedChunks: { type: 'integer' },
      lastIndexedAt: { type: ['string', 'null'], format: 'date-time' },
    },
    required: [
      'queueDepth',
      'retryingJobs',
      'failedJobs',
      'indexedDocuments',
      'indexedChunks',
      'lastIndexedAt',
    ],
  },
  IndexerReindexResponse: {
    type: 'object',
    properties: { queued: { type: 'integer' } },
    required: ['queued'],
  },
  IndexerDrainResponse: {
    type: 'object',
    properties: { processed: { type: 'integer' } },
    required: ['processed'],
  },
  JarvisIndexDocument: {
    'x-db-table': 'jarvis_index_documents',
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      sourceType: { type: 'string' },
      sourceId: { type: 'string' },
      path: { type: ['string', 'null'] },
      title: { type: ['string', 'null'] },
      contentHash: { type: ['string', 'null'] },
      mimeType: { type: ['string', 'null'] },
      sizeBytes: { type: ['integer', 'null'] },
      mtime: { type: ['string', 'null'], format: 'date-time' },
      sessionId: { type: ['string', 'null'] },
      runId: { type: ['string', 'null'] },
      userId: { type: ['string', 'null'] },
      actionId: { type: ['string', 'null'] },
      tags: {},
      metadata: { type: 'object', additionalProperties: true },
      deletedAt: { type: ['string', 'null'], format: 'date-time' },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['id', 'sourceType', 'sourceId'],
  },
  JarvisIndexChunk: {
    'x-db-table': 'jarvis_index_chunks',
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      documentId: { type: 'string', format: 'uuid' },
      chunkIndex: { type: 'integer' },
      content: { type: 'string' },
      tokenEstimate: { type: 'integer' },
      lineStart: { type: ['integer', 'null'] },
      lineEnd: { type: ['integer', 'null'] },
      metadata: { type: 'object', additionalProperties: true },
      createdAt: { type: 'string', format: 'date-time' },
    },
    required: ['id', 'documentId', 'chunkIndex', 'content'],
  },
  JarvisIndexAction: {
    'x-db-table': 'jarvis_index_actions',
    type: 'object',
    properties: {
      actionId: { type: 'string', format: 'uuid' },
      sessionId: { type: ['string', 'null'] },
      runId: { type: ['string', 'null'] },
      userId: { type: ['string', 'null'] },
      parentActionId: { type: ['string', 'null'] },
      sourceType: { type: 'string' },
      sourceId: { type: ['string', 'null'] },
      actionType: { type: 'string' },
      summary: { type: ['string', 'null'] },
      metadata: { type: 'object', additionalProperties: true },
      createdAt: { type: 'string', format: 'date-time' },
    },
    required: ['actionId', 'sourceType', 'actionType', 'createdAt'],
  },
  JarvisIndexActionLink: {
    'x-db-table': 'jarvis_index_action_links',
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      actionId: { type: 'string', format: 'uuid' },
      documentId: { type: ['string', 'null'] },
      chunkId: { type: ['string', 'null'] },
      targetType: { type: 'string' },
      targetId: { type: 'string' },
      relation: { type: 'string' },
      createdAt: { type: 'string', format: 'date-time' },
    },
    required: ['id', 'actionId', 'targetType', 'targetId', 'relation', 'createdAt'],
  },
  IndexJob: {
    'x-db-table': 'index_jobs',
    type: 'object',
    properties: {
      id: { type: 'string', format: 'uuid' },
      sourceType: { type: 'string' },
      sourceId: { type: 'string' },
      operation: { type: 'string' },
      status: { type: 'string' },
      attempts: { type: 'integer' },
      priority: { type: 'integer' },
      lastError: { type: ['string', 'null'] },
      createdAt: { type: 'string', format: 'date-time' },
      updatedAt: { type: 'string', format: 'date-time' },
    },
    required: ['id', 'sourceType', 'sourceId', 'operation', 'status'],
  },
  DebugHealthResponse: {
    type: 'object',
    properties: {
      status: { type: 'string', enum: ['ok', 'degraded'] },
      product: { type: 'string' },
      database: { type: 'string' },
      db: { type: 'boolean' },
      dbMetrics: { type: ['object', 'null'], additionalProperties: true },
      activeRuns: { type: 'integer' },
      mcp: { type: 'object', additionalProperties: true },
      embeddingQueue: { type: 'integer' },
      compute: { type: 'object', additionalProperties: true },
      cronJobs: { type: 'integer' },
      oauthProviders: { type: 'array', items: { type: 'string' } },
      microsoftSso: { type: 'object', additionalProperties: true },
      memory: { type: 'object', additionalProperties: true },
      uptime: { type: 'number' },
    },
    required: ['status', 'product', 'db'],
  },
  DebugRunsResponse: {
    type: 'object',
    properties: {
      runs: { type: 'array', items: { type: 'object', additionalProperties: true } },
      source: { type: 'string', enum: ['postgres', 'memory'] },
    },
    required: ['runs', 'source'],
  },
  DebugRunEventsResponse: {
    type: 'object',
    properties: {
      runId: { type: 'string' },
      events: { type: 'array', items: { $ref: '#/components/schemas/RunEvent' } },
      source: { type: 'string', enum: ['postgres', 'memory'] },
    },
    required: ['runId', 'events', 'source'],
  },
  SessionLiveResponse: {
    type: 'object',
    properties: {
      live: { type: 'boolean' },
      runId: { type: ['string', 'null'] },
    },
    required: ['live', 'runId'],
  },
  AguiRunInput: {
    type: 'object',
    description: 'AG-UI agent run request (threadId / messages / tools).',
    additionalProperties: true,
    properties: {
      threadId: { type: 'string' },
      runId: { type: 'string' },
      messages: { type: 'array', items: { type: 'object', additionalProperties: true } },
    },
  },
  HermesCustomEvent: {
    type: 'object',
    description: 'Custom AG-UI SSE event envelope (see packages/shared/src/agui-events.ts).',
    properties: {
      name: {
        type: 'string',
        enum: [
          'hermes.context',
          'hermes.cron.fired',
          'hermes.skill.learned',
          'hermes.title',
          'a2ui.message',
          'hermes.approval.required',
          'hermes.tool.error',
        ],
      },
      payload: { type: 'object', additionalProperties: true },
    },
    required: ['name', 'payload'],
  },
  AuthSessionResponse: {
    type: 'object',
    description: 'better-auth session payload (shape varies by plugin).',
    additionalProperties: true,
  },
}

/** Drizzle table names used for x-db-table coverage checks. */
export const DB_TABLE_ALLOWLIST = [
  'sessions',
  'messages',
  'memory',
  'skills',
  'mcp_servers',
  'mcp_connection_events',
  'cron_jobs',
  'cron_runs',
  'profiles',
  'settings',
  'api_tokens',
  'run_events',
  'jarvis_index_documents',
  'jarvis_index_chunks',
  'jarvis_index_actions',
  'jarvis_index_action_links',
  'index_jobs',
] as const
